'extensions':
- 'DeriveDataTypeable'
- 'ExtendedDefaultRules'
- 'RecordWildCards'
- 'OverloadedStrings'
'language_extensions':
- 'DeriveDataTypeable'
- 'ExtendedDefaultRules'
- 'RecordWildCards'
- 'OverloadedStrings'
'steps':
- 'imports':
    'align': 'group'
- 'language_pragmas':
    'style': 'line'
    'remove_redundant': |-
      true
- 'records': {}
- 'trailing_whitespace': {}
'columns': |-
  80
